// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCreateDateToProduct_addQuoteAcceptDateToRFQBid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCreateDateToProduct_addQuoteAcceptDateToRFQBid));
        
        string IMigrationMetadata.Id
        {
            get { return "201808082256042_addCreateDateToProduct_addQuoteAcceptDateToRFQBid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
