// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_HarmonizedCode_RFQBid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_HarmonizedCode_RFQBid));
        
        string IMigrationMetadata.Id
        {
            get { return "201910302111380_added_HarmonizedCode_RFQBid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
