// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Currency_ToolingDepositPercentage_table_CompaniesCreditRelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Currency_ToolingDepositPercentage_table_CompaniesCreditRelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201907260147296_add_Currency_ToolingDepositPercentage_table_CompaniesCreditRelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
