// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_ProcessType_ApprovedCapability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ProcessType_ApprovedCapability));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071848056_added_ProcessType_ApprovedCapability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
