// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_OrderCompanyName_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_OrderCompanyName_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "202004030413033_add_OrderCompanyName_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
