// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class replace_IsActive_with_IsCancelled_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_IsActive_with_IsCancelled_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "202007212005362_replace_IsActive_with_IsCancelled_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
