// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixDocumentIndexAndMergeLastChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixDocumentIndexAndMergeLastChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202002212107442_FixDocumentIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
