// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_ToolingSetupCharges_3_digit_PriceBreak1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_ToolingSetupCharges_3_digit_PriceBreak1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141724071_Set_ToolingSetupCharges_3_digit_PriceBreak1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
