// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_CreatedAt_StripeQbo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_CreatedAt_StripeQbo));
        
        string IMigrationMetadata.Id
        {
            get { return "202101192040300_added_CreatedAt_StripeQbo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
