// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_column_Currency_Company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_column_Currency_Company));
        
        string IMigrationMetadata.Id
        {
            get { return "202109232203367_Add_column_Currency_Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
