// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Made_ProductId_nullable_ProductStateTracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Made_ProductId_nullable_ProductStateTracking));
        
        string IMigrationMetadata.Id
        {
            get { return "202108292332209_Made_ProductId_nullable_ProductStateTracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
