// <auto-generated />
namespace Omnae.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_QuantityTemp_QuantityUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_QuantityTemp_QuantityUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "202305102344529_Add_QuantityTemp_QuantityUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
