version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2019  # Use a Windows image

jobs:
  build-and-test:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install .NET Framework Developer Pack
          command: choco install dotnetfx -y  # Install .NET Framework if needed
      - run:
          name: Restore NuGet Packages
          command: nuget restore Omnae.sln
      - run:
          name: Build Solution
          command: msbuild Omnae.sln /p:Configuration=Release
workflows:
  version: 2
  build-and-test:
    jobs:
      - build